name: Build and Push Docker Image
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Plex Tag
        id: plex_tag
        run: |
          tag=$(grep -E '^FROM linuxserver/plex:' Dockerfile | head -n1 | cut -d: -f2)
          echo "PLEX_TAG=$tag" >> $GITHUB_ENV

      - name: Build and push Docker image (latest, SHA, and Plex version)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            gwebs/plex-nvidia-patch:latest
            gwebs/plex-nvidia-patch:${{ env.PLEX_TAG }}